name: face_attendance
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  animations: ^2.0.1
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter

  get: ^4.6.1
  google_fonts: ^6.2.1
  intl: ^0.19.0
  lottie: ^3.1.2
  shimmer: ^3.0.0
  image_picker: ^1.1.2
  image_cropper: ^7.0.5
  syncfusion_flutter_calendar: ^26.1.35
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  url_launcher: ^6.0.10

  firebase_core: ^3.1.0
  firebase_auth: ^5.1.0
  cloud_firestore: ^5.0.1
  firebase_messaging: ^15.0.1
  firebase_storage: ^12.0.1
  retry: ^3.1.0
  path_provider: ^2.0.5
  http: ^1.2.1
  flutter_cache_manager: ^3.1.2
  fluttertoast: ^8.0.8
  google_maps_flutter: ^2.0.11
  get_storage: ^2.0.3
  qr_flutter: ^4.0.0
  qr_code_scanner: ^1.0.1
  connectivity_plus: ^6.0.3
  data_connection_checker_tv: ^0.3.5-nullsafety
  encrypt: ^5.0.1
  visibility_detector: ^0.4.0+2
  dartz: ^0.10.0
  worker_manager: ^4.2.5
  persistent_bottom_nav_bar: ^5.0.2
  auto_size_text: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  change_app_package_name: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/intro/
    - assets/images/logos/
    - assets/images/illustration/
    - assets/lottie/
    - assets/mapstyle/
    - shorebird.yaml
