// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANTtZiY9NszqyS367yUCdGN21fAjNYN9E',
    appId: '1:1035442472174:web:8796b345a4dd550c03dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    authDomain: 'harlem-storage2024.firebaseapp.com',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    measurementId: 'G-75CMWRDFVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBybXZnfssXy6AT7gLt2EBruAq8A17jQRA',
    appId: '1:1035442472174:android:3212a685c092b0fe03dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_PoiUINJX7tFMf7-arDEG962V4ZG6-tQ',
    appId: '1:1035442472174:ios:c9c10525501042f303dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    iosBundleId: 'com.abdulmomin.faceAttendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_PoiUINJX7tFMf7-arDEG962V4ZG6-tQ',
    appId: '1:1035442472174:ios:c9c10525501042f303dfff',
    messagingSenderId: '1035442472174',
    projectId: 'harlem-storage2024',
    databaseURL: 'https://harlem-storage2024-default-rtdb.firebaseio.com',
    storageBucket: 'harlem-storage2024.appspot.com',
    iosBundleId: 'com.abdulmomin.faceAttendance',
  );
}
